<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $typeLabel }} - Glamora</title>
<style>
    body { font-family: 'Helvetica', Arial, sans-serif; padding: 25px; color: #1a1a1a; }
    .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #fce4ec; padding-bottom: 12px; }
    .header h1 { color: #E91E8C; font-size: 22px; margin: 0 0 6px; }
    .header .sub { color: #888; font-size: 11px; }
    .date-range { background: #fff0f7; display: inline-block; padding: 5px 16px; border-radius: 20px; font-size: 11px; color: #c2185b; font-weight: bold; margin-top: 6px; }

    .summary-grid { display: flex; gap: 12px; margin-bottom: 20px; }
    .summary-card { background: #fff0f7; border: 1px solid #fce4ec; border-radius: 10px; padding: 10px 18px; flex: 1; text-align: center; }
    .summary-card .label { font-size: 9px; text-transform: uppercase; color: #c2185b; font-weight: bold; }
    .summary-card .value { font-size: 17px; font-weight: 800; color: #1a1a1a; margin-top: 3px; }

    table.data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    table.data-table th { background: #fce4ec; color: #c2185b; padding: 8px 10px; font-size: 10px; text-align: left; }
    table.data-table td { padding: 7px 10px; border-bottom: 1px solid #f5eef2; font-size: 10.5px; }
    table.data-table tr:nth-child(even) { background: #fffafc; }

    .empty { text-align: center; padding: 30px; color: #aaa; font-size: 12px; }
    .footer { text-align: center; margin-top: 22px; padding-top: 12px; border-top: 1px solid #fce4ec; font-size: 9.5px; color: #aaa; }
</style>
</head>
<body>

<div class="header">
    <h1>Glamora</h1>
    <div class="sub">{{ $typeLabel }}</div>
    <div class="date-range">{{ \Carbon\Carbon::parse($fromDate)->format('d M Y') }} — {{ \Carbon\Carbon::parse($toDate)->format('d M Y') }}</div>
</div>

@if(count($report['summary']) > 0)
<div class="summary-grid">
    @foreach($report['summary'] as $label => $value)
    <div class="summary-card">
        <div class="label">{{ $label }}</div>
        <div class="value">{{ $value }}</div>
    </div>
    @endforeach
</div>
@endif

@if(count($report['rows']) > 0)
<table class="data-table">
    <thead>
        <tr>
            @foreach($report['columns'] as $col)
            <th>{{ $col['label'] }}</th>
            @endforeach
        </tr>
    </thead>
    <tbody>
        @foreach($report['rows'] as $row)
        <tr>
            @foreach($report['columns'] as $col)
            <td>{{ $row[$col['key']] ?? '—' }}</td>
            @endforeach
        </tr>
        @endforeach
    </tbody>
</table>
@else
<div class="empty">No records found for this date range.</div>
@endif

<div class="footer">
    <p>Generated by: {{ auth()->user()->name ?? 'Admin' }} | {{ now()->format('d M Y, h:i A') }}</p>
    <p>&copy; {{ now()->year }} Glamora — All rights reserved.</p>
</div>

</body>
</html>